# Kaggle Learn - Intro to Machine Learning
---

## 1. How Models Work
---
Basic introduction terminology:
- **Training data** - data used to fit the model.
- **Training (fitting) the model** - process of finding data patterns.
- **Decision tree** - Simple structure, every node is the criterion, and there are two possible outcomes, whether the criterion is met or no.
- **Leaf** - Bottom point of the tree, where a prediction is made.

## 2. Basic Data Exploration
---
We'll be using the Iowa housing price dataset, same as the chapter's exercises.

Well import Pandas library to access DataFrame, to view and manipulate our data.

In [3]:
import pandas as pd
iowa_file_path = '/kaggle/input/datasets/dansbecker/home-data-for-ml-course/train.csv'

home_data = pd.read_csv(iowa_file_path) # loading the data

In [4]:
# Reviewing data using .describe()
home_data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [5]:
# Accessing the top 5 rows uisng head()
home_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## 3. Your First Machine Learning Model
---
As we can see, there are 81 columns - too many for simple analysis. The question is how to choose relevant columns i.e. selecting right data for modeling.

To subset the data, we need to select the **prediction target** and **features**.

First, let's look at all dataset columns.

In [6]:
home_data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

Clearly, the **prediction target** is SalePrice.

And for the **features**, we will choose LotArea, YearBuilt, 1stFlrSF, 2ndFlrSF, FullBath, BedroomAbvGr and TotRmsAbvGrd.

In [8]:
y = home_data.SalePrice
features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']

X = home_data[features]

Let's get a closer look on the data chosen for modeling. Again, we will use descrbibe() and head() methods from pandas.

In [10]:
X.describe()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,10516.828082,1971.267808,1162.626712,346.992466,1.565068,2.866438,6.517808
std,9981.264932,30.202904,386.587738,436.528436,0.550916,0.815778,1.625393
min,1300.000000,1872.000000,334.000000,0.000000,0.000000,0.000000,2.000000
25%,7553.500000,1954.000000,882.000000,0.000000,1.000000,2.000000,5.000000
50%,9478.500000,1973.000000,1087.000000,0.000000,2.000000,3.000000,6.000000
75%,11601.500000,2000.000000,1391.250000,728.000000,2.000000,3.000000,7.000000
max,215245.000000,2010.000000,4692.000000,2065.000000,3.000000,8.000000,14.000000

In [11]:
X.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
0,8450,2003,856,854,2,3,8
1,9600,1976,1262,0,2,3,6
2,11250,2001,920,866,2,3,6
3,9550,1915,961,756,1,3,7
4,14260,2000,1145,1053,2,4,9

**Model building**.

There are four steps to building and using a model:
- **Define model type and parameters**
- **Model fitting**
- **Making predictions**
- **Model evaluation**: determining how accurate the predictions are.

For this problem, we will use <u>DecisionTreeRegressor</u> from sklearn.tree

In [12]:
# Model specyfing and fitting
from sklearn.tree import DecisionTreeRegressor

iowa_model = DecisionTreeRegressor(random_state = 1) # specifying a model, random_state - seed
iowa_model.fit(X, y) # fitting the model

DecisionTreeRegressor(random_state=1)

In [13]:
# Making predictions
predictions = iowa_model.predict(X) # X - our data for model fitting
print(predictions)

[208500. 181500. 223500. ... 266500. 142125. 147500.]

Let's compare the predictions to the actual values for the first five rows.

In [14]:
print("First five houses:")
head_houses = X.head()
print("Predicted prices:")
print(iowa_model.predict(head_houses))
print("Real prices:")
print(y.head())

First five houses:
Predicted prices:
[208500. 181500. 223500. 140000. 250000.]
Real prices:
0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

## 4. Model Validation
---

Before, we used all the train data to fit our model, and we also evaluated the model on the test data. This is not a good practice, because the model has already seen all the train data, and it will work well for the data it was trained on, but it will perform badly for the new data - this is called **overfitting**.

Therefore, we will split our data on two subsets - one for training, and the other one for validation.

In [17]:
# train_test_split function splits the data
from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 1)

Now, we will repeat the model specifying and fitting  process, but **only on the train data** subset. 

Similarly, we will make predictions **only on the validation data** subset.

In [18]:
iowa_model = DecisionTreeRegressor(random_state=1)
iowa_model.fit(train_X,train_y)

DecisionTreeRegressor(random_state=1)

In [19]:
val_predictions = iowa_model.predict(val_X)

Now, let's compare new predictions to the actual values.

In [20]:
print("Predicted values:")
print(val_predictions[:5])
print("Real values:")
print(val_y.head())

Predicted values:
[186500. 184000. 130000.  92000. 164500.]
Real values:
258     231500
267     179500
288     122000
649      84500
1233    142000
Name: SalePrice, dtype: int64

To evaluate the model, we need to use some metrics. **Mean Absolute Error** gives us the mean value of absolute errors for all predictions, i.e. "how for" are our predictions on average.

In [21]:
from sklearn.metrics import mean_absolute_error

val_mae = mean_absolute_error(val_y, val_predictions)
print(val_mae)

29652.931506849316

## 5. Underfitting and Overfitting
---